### PR TITLE
Issue/#56

### PR DESCRIPTION
**Pull request by JackTheHack**
Added handling for serialized items, added fix for empty linked template with null __basetemplate, added unit tests

### CODE REVIEW

**Comment by JackTheHack** [comment]
I'm not sure if doing everything correctly. I'm not familiar with pull request process in GitHub. Please correct me if I'm doing the process stuff wrong.

**Comment by sergeyshushlyapin** [comment]
@JackTheHack, thank you for your time. I appreciate the efforts you make to improve FakeDb.

Github reports *"We can’t automatically merge this pull request."* meaning that you're based on some obsolete revision. I've closed #55 couple of days ago. Could you please rebase to the latest version and check if your scenario is still reproducible? If yes, an updated PR is welcome ;)

BTW, could you please elaborate what does *Null Template* mean. Thank you.

**Comment by JackTheHack** [comment]
@sergeyshushlyapin I included the unit test and serialization item for the Null Base Template case.

In basic, it happened when I was deserializing the Folder item. When the FakeDB was deserializing linked template the __basetemplate field was null and it thrown an error.

**Comment by sergeyshushlyapin** [comment]
Merged with few minor improvements:
- Reverted commit *"Update SerializedIdToPathDictionary.cs"* (https://github.com/sergeyshushlyapin/Sitecore.FakeDb/commit/f8bf50f8d87dd05370e4932cd5aa816bf8e83b44). The fix has been implemented in https://github.com/sergeyshushlyapin/Sitecore.FakeDb/issues/55
- `NullBaseTemplates.item` and `Global.item` renamed to `Item Without BaseTemplates.item` and `New Item Without BaseTemplates.item` correspondingly

Thank you for contribution!

**Pull request merged**
