### PR TITLE
Only reuse generated templates. This closes #34

### LINKED ISSUE #34: Automatic template generation needs to be a little smarter
FakeDb will generate a template for a `DbItem` that was not given a specific template. FakeDb also reuses the template from the sibling item added previously in case item definitions match (i.e. same fields). I believe FakeDb **shouldn't reuse templates unless those were auto-generated**. Here's an example:

```csharp
using (var db = new Db
{
    new DbTemplate("Site Root", new ID(myID),
    new DbItem("site", ID.NewID, new ID(myID))
    {
        new DbItem("home")
    },
    new DbItem("outside")
})
{
    var home = db.GetItem("/sitecore/content/site/home");
    var outside = db.GetItem("/sitecore/content/outside");

    outside.TemplateID.Should().NotBe(myID) // <-- Fails
}
```

`outside` item will be created with `myID` as its `TemplateID`. I think it should have been given its own template. 

@sergeyshushlyapin , let me know what you think. I will send a pull request shortly :)

### PR DESCRIPTION
**Pull request by pveller**

### CODE REVIEW

**Comment by sergeyshushlyapin** [comment]
Merged. Thank you!

**Comment by pveller** [comment]
I was thinking we can actually make it even smarter and reuse any generated template that matches the field definition. No need to limit to last sibling. No harm in doing that. Right? One or two lines of code and a few tests :) if you agree I will do tonight while it's still "hot".

**Comment by sergeyshushlyapin** [comment]
Yep. Sounds reasonable.

**Comment by pveller** [comment]
Will do

**Pull request merged**
